### PR TITLE
Add man page

### PR DESCRIPTION
**Pull request by leegarrett**
Hi,

I've written a man page for the Debian package of AusweisApp2, and I'm hoping this is useful for other distros, too. My original MR for Debian is at https://salsa.debian.org/debian/ausweisapp2/-/merge_requests/2. The maintainer has asked me to send it upstream.

### CODE REVIEW

**Comment by misery** [comment]
Thanks! Could you sign the CLA here?

**Comment by leegarrett** [comment]
> Thanks! Could you sign the CLA here?

Done.

**Comment by misery** [comment]
Thanks, we merged it into our internal repository and ship it soon with next major release. We changed some tiny stuff because the old UI is removed.

**Comment by leegarrett** [comment]
Thanks!

**Pull request closed without merging**
