### PR TITLE
Fix build and QML with Qt 6.4

### PR DESCRIPTION
**Pull request by lunaryorn**

### CODE REVIEW

**Review by MartinX3 — APPROVED** [review]

**Review by MartinX3 — APPROVED** [review]

**Review by MartinX3 — APPROVED** [review]

**Review by MartinX3 — APPROVED** [review]

**Comment by moritzhoewer** [comment]
Thanks @lunaryorn - this PR fixed the build issues I had with QT 6.4 on Arch Linux and I can use the app again

**Comment by misery** [comment]
Thank you very much. We already fixed this a little bit different in our internal repository. :-) This will be fixed in 1.24.3.

**Comment by MartinX3** [comment]
"internal repository", the spirit of open source.

Sounds like a violation of the EUPL 1.2 license...
And afraids people from submitting pull requests.

**Comment by lunaryorn** [comment]
@misery Thank you very much 🙏🏿  I'm looking forward to the new version 🙂

**Pull request closed without merging**
