### PR TITLE
Add initial support for Travis CI

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by GitMensch** [comment]
@misery: I highly suggest to register for coverity scan and automate the checks via Travis - see https://scan.coverity.com/github

**Comment by misery** [comment]
@GitMensch 
Thanks for the suggestion.
We already registered coverity scan: https://scan.coverity.com/projects/governikus-ausweisapp2

**Comment by GitMensch** [comment]
@misery This is good. What do you think about adding the badge to the readme?
For example with

[Coverity Scan Build Status](https://scan.coverity.com/projects/governikus-ausweisapp2)

**Comment by misery** [comment]
@GitMensch 
Well, I like those badges. But coverity scan is checked carefully and there are some false-positives like these "5 new defects". We do not want to scare people about security issues that do not exist.

**Comment by GitMensch** [comment]
@misery I see. But if you are investigating these in general and mark false-positives as false-positives + trigger recheck those should go away from the badge *and* you show to users that you actually do coverity check.

**Pull request merged**
