### PR TITLE
Use 5.9 for appveyor as it is mapped to current version

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by chcg** [comment]
@misery See https://github.com/chcg/AusweisApp2/commits/appveyor_qt5_10 for build with QT 5.10.0. Undef of min and max is needed, because commit below seems to be not part of the release 5.10.0 yet:

https://code.qt.io/cgit/qt/qtbase.git/commit/src/corelib/global/qrandom.h?h=dev&id=656804b9645a83430dcd0929c49b4065d43d7990

**Comment by misery** [comment]
Thanks! I know the problem of min/max - I'm the reporter of that bug report. :-)

I think we should use 5.9 for the moment. Looks like they will delete 5.10.0 if 5.10.1 is available.

**Comment by chcg** [comment]
Now I see https://bugreports.qt.io/browse/QTBUG-65414, but how do you think to handle it in Radomizer.cpp? Just update the current check from

#if (QT_VERSION >= QT_VERSION_CHECK(5, 10, 0))

to

#if (QT_VERSION >= QT_VERSION_CHECK(5, 10, 1))?

**Comment by misery** [comment]
Yes, I think so. Qt 5.10.0 as a lot of bugs - so it should be the best to skip it.

**Comment by chcg** [comment]
@misery See https://ci.appveyor.com/project/chcg/ausweisapp2/build/1.14.1-63 for a debug testbuild with Qt 5.10.1. And https://ci.appveyor.com/project/chcg/ausweisapp2/build/64 for the release version. Do you think it is time to update?

**Comment by GitMensch** [comment]
I'd create an Issue for this but as these are not active posting it here.

@misery 
Is there any reason to not integrate the produced binaries (MSI) into the build artifacts?
This would allow a direct download of the community-build, too.

Is there any reason to not integrate [Travis][1]/[AppVeyor][2] in this repository (which would both show the current build process (when Badges are added to the README) and the status of PR (when service hooks are enabled) without the need to manually check if everything is fine)?

[1]:https://travis-ci.org/Governikus/AusweisApp2
[2]:https://ci.appveyor.com/project/GovernikusAusweisApp2/ausweisapp2

**Comment by misery** [comment]
@chcg
Thanks for testing again. We already updated Qt for the next major version on our internal CI and checked current stable version.
There should be no problem that needs to be fixed.
I think the problem is in the setup of testing environment as the failing tests do a lot of networking stuff. I need to investigate the AppVeyor environment a little bit more.

@GitMensch
Yeah, we do not want to provide multiple "official" versions of AusweisApp2 to avoid confused users. Also it is not possible to use the same official signing key.

Feel free to create a pull request for the badges. :-) Travis and AppVeyor are already registered for the community branch and pull requests.

**Pull request merged**
