### PR TITLE
Adding structure for building RPMs via COPR

### PR DESCRIPTION
**Pull request by jtalir**

### CODE REVIEW

**Comment by besser82** [comment]
@jtalir I'm currently packaging the AusweisApp for the official Fedora repositories, FYI.

**Comment by jtalir** [comment]
Great, where can I find rpms? I don't see it in F32 official repositories.

**Comment by besser82** [comment]
I'm currently working on that packaging…  I may take a few days until I'm finished with it, as I need to clarify EUPL v1.2 licensing status, and get a bit familiar with the way CMake is utilized in the build process.

**Comment by besser82** [comment]
> Great, where can I find rpms? I don't see it in F32 official repositories.

AusweisApp2-1.20.1 has just been imported into the official Fedora repositories.  See [Bodhi](https://bodhi.fedoraproject.org/updates/?packages=AusweisApp2) for the status of updates processing.

Would you mind to please remove the COPR repository as soon as those update are stable?

**Comment by jtalir** [comment]
Nice, I checked installation on F32 from Bodhi and it works fine. I removed project from COPR.

**Comment by misery** [comment]
Thanks for the package! I'll close this now.

**Pull request closed without merging**
